// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtsVk1PqWYnMVxx_Zbl24N1qfjzxbZ8_0',
    appId: '1:374709527171:web:d4a6a4388bef40e54af1b6',
    messagingSenderId: '374709527171',
    projectId: 'socials-forall',
    authDomain: 'socials-forall.firebaseapp.com',
    storageBucket: 'socials-forall.firebasestorage.app',
    measurementId: 'G-ED5E6PWFER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSR1Lag1xZnV6haGDUB9xeX107tjg5iIc',
    appId: '1:374709527171:android:9ee444db5723210d4af1b6',
    messagingSenderId: '374709527171',
    projectId: 'socials-forall',
    storageBucket: 'socials-forall.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXxXNOrD8v72xj9bjRQ_PP7tGlHyVrHA8',
    appId: '1:374709527171:ios:81d93653be0ab8cc4af1b6',
    messagingSenderId: '374709527171',
    projectId: 'socials-forall',
    storageBucket: 'socials-forall.firebasestorage.app',
    iosBundleId: 'com.example.socials',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXxXNOrD8v72xj9bjRQ_PP7tGlHyVrHA8',
    appId: '1:374709527171:ios:81d93653be0ab8cc4af1b6',
    messagingSenderId: '374709527171',
    projectId: 'socials-forall',
    storageBucket: 'socials-forall.firebasestorage.app',
    iosBundleId: 'com.example.socials',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtsVk1PqWYnMVxx_Zbl24N1qfjzxbZ8_0',
    appId: '1:374709527171:web:ef8274606b5f42584af1b6',
    messagingSenderId: '374709527171',
    projectId: 'socials-forall',
    authDomain: 'socials-forall.firebaseapp.com',
    storageBucket: 'socials-forall.firebasestorage.app',
    measurementId: 'G-WCWFQKMREQ',
  );
}
